# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simpleCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(393, 372)
        self.lineEditInput = QtWidgets.QLineEdit(Dialog)
        self.lineEditInput.setGeometry(QtCore.QRect(20, 150, 351, 41))
        self.lineEditInput.setObjectName("lineEditInput")
        self.listWidgetRecord = QtWidgets.QListWidget(Dialog)
        self.listWidgetRecord.setGeometry(QtCore.QRect(20, 21, 351, 131))
        self.listWidgetRecord.setObjectName("listWidgetRecord")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 280, 51, 31))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 280, 51, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 280, 51, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 240, 51, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 240, 51, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 240, 51, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 200, 51, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 200, 51, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 200, 51, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_divide = QtWidgets.QPushButton(Dialog)
        self.pushButton_divide.setGeometry(QtCore.QRect(200, 200, 51, 31))
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_mult = QtWidgets.QPushButton(Dialog)
        self.pushButton_mult.setGeometry(QtCore.QRect(200, 240, 51, 31))
        self.pushButton_mult.setObjectName("pushButton_mult")
        self.pushButton_sub = QtWidgets.QPushButton(Dialog)
        self.pushButton_sub.setGeometry(QtCore.QRect(200, 280, 51, 31))
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.pushButton_add = QtWidgets.QPushButton(Dialog)
        self.pushButton_add.setGeometry(QtCore.QRect(200, 320, 51, 31))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_0 = QtWidgets.QPushButton(Dialog)
        self.pushButton_0.setGeometry(QtCore.QRect(20, 320, 51, 31))
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_comma = QtWidgets.QPushButton(Dialog)
        self.pushButton_comma.setGeometry(QtCore.QRect(80, 320, 51, 31))
        self.pushButton_comma.setObjectName("pushButton_comma")
        self.pushButton_modulo = QtWidgets.QPushButton(Dialog)
        self.pushButton_modulo.setGeometry(QtCore.QRect(140, 320, 51, 31))
        self.pushButton_modulo.setObjectName("pushButton_modulo")
        self.pushButton_undo = QtWidgets.QPushButton(Dialog)
        self.pushButton_undo.setGeometry(QtCore.QRect(260, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_undo.setFont(font)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.pushButton_clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_clear.setGeometry(QtCore.QRect(320, 200, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_leftParenthesis = QtWidgets.QPushButton(Dialog)
        self.pushButton_leftParenthesis.setGeometry(QtCore.QRect(260, 240, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_leftParenthesis.setFont(font)
        self.pushButton_leftParenthesis.setObjectName("pushButton_leftParenthesis")
        self.pushButton_rightParenthesis = QtWidgets.QPushButton(Dialog)
        self.pushButton_rightParenthesis.setGeometry(QtCore.QRect(320, 240, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_rightParenthesis.setFont(font)
        self.pushButton_rightParenthesis.setObjectName("pushButton_rightParenthesis")
        self.pushButton_square = QtWidgets.QPushButton(Dialog)
        self.pushButton_square.setGeometry(QtCore.QRect(260, 280, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_square.setFont(font)
        self.pushButton_square.setObjectName("pushButton_square")
        self.pushButton_root = QtWidgets.QPushButton(Dialog)
        self.pushButton_root.setGeometry(QtCore.QRect(320, 280, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_root.setFont(font)
        self.pushButton_root.setObjectName("pushButton_root")
        self.pushButton_result = QtWidgets.QPushButton(Dialog)
        self.pushButton_result.setGeometry(QtCore.QRect(260, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_result.setFont(font)
        self.pushButton_result.setObjectName("pushButton_result")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_1.setText(_translate("Dialog", "1"))
        self.pushButton_1.setShortcut(_translate("Dialog", "1"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_3.setShortcut(_translate("Dialog", "3"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_5.setShortcut(_translate("Dialog", "5"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_6.setShortcut(_translate("Dialog", "6"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_8.setShortcut(_translate("Dialog", "8"))
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_9.setShortcut(_translate("Dialog", "9"))
        self.pushButton_divide.setText(_translate("Dialog", "➗"))
        self.pushButton_divide.setShortcut(_translate("Dialog", "/"))
        self.pushButton_mult.setText(_translate("Dialog", "❌"))
        self.pushButton_mult.setShortcut(_translate("Dialog", "*"))
        self.pushButton_sub.setText(_translate("Dialog", "➖"))
        self.pushButton_sub.setShortcut(_translate("Dialog", "-"))
        self.pushButton_add.setText(_translate("Dialog", "➕"))
        self.pushButton_add.setShortcut(_translate("Dialog", "+"))
        self.pushButton_0.setText(_translate("Dialog", "0"))
        self.pushButton_comma.setText(_translate("Dialog", ","))
        self.pushButton_modulo.setText(_translate("Dialog", "%"))
        self.pushButton_undo.setText(_translate("Dialog", "↶"))
        self.pushButton_undo.setShortcut(_translate("Dialog", "Backspace"))
        self.pushButton_clear.setText(_translate("Dialog", "C"))
        self.pushButton_leftParenthesis.setText(_translate("Dialog", "("))
        self.pushButton_rightParenthesis.setText(_translate("Dialog", ")"))
        self.pushButton_square.setText(_translate("Dialog", "2"))
        self.pushButton_root.setText(_translate("Dialog", "√"))
        self.pushButton_result.setText(_translate("Dialog", "="))
        self.pushButton_result.setShortcut(_translate("Dialog", "Return"))


